import type { BookingStatus, Role } from '@prisma/client';
import { prisma } from '../../lib/prisma.js';
import { AppError } from '../../lib/http.js';

const include = { customer: { select: { id: true, name: true, email: true } }, service: { include: { category: true, provider: { select: { id: true, name: true } } } } } as const;
type Actor = { id: string; role: Role };
export const bookingService = {
  async customer(actor: Actor, page: number, limit: number, skip: number) { const where = { customerId: actor.id, isDeleted: false }; const [items, total] = await prisma.$transaction([prisma.booking.findMany({ where, include, orderBy: { scheduledAt: 'desc' }, skip, take: limit }), prisma.booking.count({ where })]); return { items, total }; },
  async incoming(actor: Actor, page: number, limit: number, skip: number) { const where = { isDeleted: false, ...(actor.role === 'PROVIDER' ? { service: { providerId: actor.id } } : {}) }; const [items, total] = await prisma.$transaction([prisma.booking.findMany({ where, include, orderBy: { scheduledAt: 'desc' }, skip, take: limit }), prisma.booking.count({ where })]); return { items, total }; },
  async byId(id: string, actor: Actor) { const data = await prisma.booking.findFirst({ where: { id, isDeleted: false }, include }); if (!data) throw new AppError(404, 'Booking not found'); if (actor.role === 'CUSTOMER' && data.customerId !== actor.id) throw new AppError(403, 'You can only view your own bookings'); if (actor.role === 'PROVIDER' && data.service.providerId !== actor.id) throw new AppError(403, 'You can only view bookings for your services'); return data; },
  async create(actor: Actor, input: { serviceId: string; scheduledAt: string; address: string; note?: string }) { const service = await prisma.service.findFirst({ where: { id: input.serviceId, isDeleted: false, status: 'ACTIVE' } }); if (!service) throw new AppError(404, 'Service not found'); return prisma.booking.create({ data: { serviceId: service.id, scheduledAt: new Date(input.scheduledAt), address: input.address, note: input.note, total: service.price, customerId: actor.id } }); },
  async update(id: string, actor: Actor, input: { status?: BookingStatus; scheduledAt?: string; address?: string; note?: string }) { const current = await prisma.booking.findUnique({ where: { id }, include: { service: true } }); if (!current) throw new AppError(404, 'Booking not found'); const isCustomer = current.customerId === actor.id; const isProvider = current.service.providerId === actor.id; if (!isCustomer && !isProvider && actor.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); const data = actor.role === 'CUSTOMER' ? { ...(input.status === 'CANCELLED' ? { status: 'CANCELLED' as const } : {}), ...(input.address ? { address: input.address } : {}), ...(input.note !== undefined ? { note: input.note } : {}) } : { ...(input.status ? { status: input.status } : {}), ...(input.scheduledAt ? { scheduledAt: new Date(input.scheduledAt) } : {}) }; return prisma.booking.update({ where: { id }, data }); },
  async remove(id: string, actor: Actor) { const current = await prisma.booking.findUnique({ where: { id } }); if (!current) throw new AppError(404, 'Booking not found'); if (current.customerId !== actor.id && actor.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); return prisma.booking.update({ where: { id }, data: { isDeleted: true } }); },
};
