import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,CalendarDays,Check,Clock,Menu,Search,ShieldCheck,Sparkles,Star,X}from'lucide-react';import{api,Category,Service}from'./api';import'./styles.css';import'./auth.css';
type User={id:string;name:string;email:string};
function App(){
 const[services,setServices]=useState<Service[]>([]),[categories,setCategories]=useState<Category[]>([]),[selected,setSelected]=useState<Service|null>(null),[authOpen,setAuthOpen]=useState(false),[mode,setMode]=useState<'login'|'register'>('login'),[user,setUser]=useState<User|null>(null),[notice,setNotice]=useState(''),[authError,setAuthError]=useState(''),[authLoading,setAuthLoading]=useState(false);
 useEffect(()=>{Promise.all([api<Service[]>('/services'),api<Category[]>('/categories')]).then(([s,c])=>{setServices(s);setCategories(c)}).catch(()=>setNotice('Connect the API and seed the database to load live services.'));if(localStorage.getItem('token'))api<User>('/users/me').then(setUser).catch(()=>localStorage.removeItem('token'))},[]);
 const loadCategory=(id?:string)=>api<Service[]>(`/services${id?`?categoryId=${id}`:''}`).then(setServices);
 const auth=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setAuthError('');setAuthLoading(true);try{const data=await api<{token:string;user:User}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))});localStorage.setItem('token',data.token);setUser(data.user);setAuthOpen(false);setNotice(`Welcome${mode==='register'?' to Servora':''}, ${data.user.name}.`)}catch(e){setAuthError((e as Error).message)}finally{setAuthLoading(false)}};
 const book=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!user){setSelected(null);setAuthOpen(true);return}const f=new FormData(e.currentTarget);try{await api('/bookings',{method:'POST',body:JSON.stringify({serviceId:selected!.id,scheduledAt:new Date(String(f.get('scheduledAt'))).toISOString(),address:f.get('address'),note:f.get('note')})});setSelected(null);setNotice('Your booking is confirmed in our system.')}catch(e){setNotice((e as Error).message)}};
 return <><header><a className="brand" href="#"><span>S</span>servora</a><nav><a href="#services">Services</a><a href="#how">How it works</a><a href="#trust">Why Servora</a></nav><div className="actions">{user?<><span className="hello">Hi, {user.name.split(' ')[0]}</span><button className="link" onClick={()=>{localStorage.removeItem('token');setUser(null)}}>Log out</button></>:<button className="link" onClick={()=>setAuthOpen(true)}>Log in</button>}<button className="primary" onClick={()=>document.getElementById('services')?.scrollIntoView()}>Find a service</button><Menu className="menu"/></div></header>
 <main><section className="hero"><div className="eyebrow"><Sparkles size={15}/> Exceptional help, thoughtfully delivered</div><h1>Life runs better<br/>with a little <em>help.</em></h1><p>Trusted local professionals for the things that matter—beautifully simple to book, reassuring from start to finish.</p><div className="search"><Search/><input placeholder="What can we help with?"/><button onClick={()=>document.getElementById('services')?.scrollIntoView()}>Explore services <ArrowRight size={18}/></button></div><div className="proof"><span><Check/> Vetted professionals</span><span><ShieldCheck/> Satisfaction guaranteed</span><span><Star/> Loved by 12,000+ homes</span></div></section>
 <section className="categories"><div className="section-title"><div><small>EVERYDAY, ELEVATED</small><h2>What can we take care of?</h2></div><button className="link" onClick={()=>loadCategory()}>View all services <ArrowRight size={16}/></button></div><div className="category-grid">{categories.map(c=><button key={c.id} onClick={()=>loadCategory(c.id)}><b>{c.icon||'✦'}</b><span>{c.name}</span><ArrowRight/></button>)}</div></section>
 <section id="services" className="services"><div className="section-title"><div><small>CURATED FOR YOU</small><h2>Services people love</h2></div></div>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}><X size={16}/></button></div>}<div className="cards">{services.map(s=>{const rating=s.reviews.length?(s.reviews.reduce((a,r)=>a+r.rating,0)/s.reviews.length).toFixed(1):'New';return <article key={s.id}><div className="image" style={{backgroundImage:`url(${s.image})`}}><span>{s.category.name}</span></div><div className="card-body"><div className="rating"><Star size={14} fill="currentColor"/> {rating} {s.reviews.length>0&&<i>({s.reviews.length})</i>}</div><h3>{s.title}</h3><p>{s.description}</p><div className="meta"><span><Clock size={16}/>{s.duration} min</span><strong>From ${Number(s.price).toFixed(0)}</strong></div><button onClick={()=>setSelected(s)}>Book this service <ArrowRight size={17}/></button></div></article>})}</div></section>
 <section id="how" className="steps"><small>EFFORTLESS BY DESIGN</small><h2>More ease. Less to-do.</h2><div><article><b>01</b><h3>Tell us what you need</h3><p>Choose a service and the time that works for your life.</p></article><article><b>02</b><h3>Meet your professional</h3><p>Every provider is carefully vetted, rated, and ready to help.</p></article><article><b>03</b><h3>Enjoy the difference</h3><p>Relax while it gets done—backed by our happiness promise.</p></article></div></section>
 <section id="trust" className="promise"><div><small>THE SERVORA PROMISE</small><h2>Care you can count on.</h2><p>We're building a better way to ask for help. Every detail—from who arrives at your door to how support responds—is designed around your peace of mind.</p><button className="primary">Our quality standard <ArrowRight size={17}/></button></div><blockquote>“The kind of service that makes you wonder how you ever managed without it.”<footer>— Maya T., Servora member</footer></blockquote></section></main>
 <footer className="footer"><a className="brand"><span>S</span>servora</a><p>More time for what matters.</p><small>© 2026 Servora. Thoughtful help, close to home.</small></footer>
 {authOpen&&<div className="modal"><form onSubmit={auth}><button type="button" className="close" onClick={()=>setAuthOpen(false)}><X/></button><small>WELCOME TO SERVORA</small><h2>{mode==='login'?'Good to see you again.':'Create your account.'}</h2>{mode==='register'&&<label>Name<input name="name" required minLength={2}/></label>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required minLength={8}/></label>{authError&&<div className="form-error">{authError}</div>}<button className="primary" disabled={authLoading}>{authLoading?'Please wait…':mode==='login'?'Log in':'Create account'} {!authLoading&&<ArrowRight size={17}/>}</button><p>{mode==='login'?"New here? ":'Already a member? '}<button type="button" className="link" onClick={()=>{setMode(mode==='login'?'register':'login');setAuthError('')}}>{mode==='login'?'Create an account':'Log in'}</button></p></form></div>}
 {selected&&<div className="modal"><form onSubmit={book}><button type="button" className="close" onClick={()=>setSelected(null)}><X/></button><small>BOOK YOUR SERVICE</small><h2>{selected.title}</h2><div className="booking-price">${Number(selected.price).toFixed(0)} <span>· {selected.duration} minutes</span></div><label>Date & time<input name="scheduledAt" type="datetime-local" required/></label><label>Service address<input name="address" required minLength={5}/></label><label>Anything we should know?<textarea name="note" rows={3}/></label><button className="primary"><CalendarDays size={17}/> Confirm booking</button></form></div>}
 </>}
createRoot(document.getElementById('root')!).render(<App/>);
