import { Router, type NextFunction, type Request, type Response } from 'express';
import type { Role } from '@prisma/client';
import { prisma } from '../lib/prisma.js';
import { auth } from '../middleware/auth.js';
import { AppError, ok } from '../lib/http.js';

const idOf = (req: Request) => String(req.params.id);
const requireRole = (...roles: Role[]) => (req: Request, _res: Response, next: NextFunction) =>
  roles.includes(req.user!.role) ? next() : next(new AppError(403, 'You do not have permission to perform this action'));

export const categories = Router();
categories.get('/', async (_req, res, next) => { try { ok(res, 'Categories retrieved successfully', await prisma.category.findMany({ where: { isDeleted: false }, orderBy: { name: 'asc' } })); } catch (error) { next(error); } });
categories.get('/:id', async (req, res, next) => { try { const data = await prisma.category.findFirst({ where: { id: idOf(req), isDeleted: false } }); if (!data) throw new AppError(404, 'Category not found'); ok(res, 'Category retrieved successfully', data); } catch (error) { next(error); } });
categories.post('/', auth, requireRole('ADMIN'), async (req, res, next) => { try { ok(res, 'Category created successfully', await prisma.category.create({ data: req.body }), 201); } catch (error) { next(error); } });
categories.patch('/:id', auth, requireRole('ADMIN'), async (req, res, next) => { try { ok(res, 'Category updated successfully', await prisma.category.update({ where: { id: idOf(req) }, data: req.body })); } catch (error) { next(error); } });
categories.delete('/:id', auth, requireRole('ADMIN'), async (req, res, next) => { try { ok(res, 'Category deleted successfully', await prisma.category.update({ where: { id: idOf(req) }, data: { isDeleted: true } })); } catch (error) { next(error); } });

const serviceInclude = { category: true, provider: { select: { id: true, name: true, avatar: true } }, reviews: { where: { isDeleted: false } } } as const;
export const services = Router();
services.get('/', async (req, res, next) => { try { const search = req.query.search ? String(req.query.search) : undefined; ok(res, 'Services retrieved successfully', await prisma.service.findMany({ where: { isDeleted: false, status: 'ACTIVE', ...(req.query.categoryId ? { categoryId: String(req.query.categoryId) } : {}), ...(search ? { OR: [{ title: { contains: search, mode: 'insensitive' } }, { description: { contains: search, mode: 'insensitive' } }] } : {}) }, include: serviceInclude, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
services.get('/mine', auth, requireRole('PROVIDER', 'ADMIN'), async (req, res, next) => { try { ok(res, 'Managed services retrieved successfully', await prisma.service.findMany({ where: { isDeleted: false, ...(req.user!.role === 'PROVIDER' ? { providerId: req.user!.id } : {}) }, include: serviceInclude, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
services.get('/:id', async (req, res, next) => { try { const data = await prisma.service.findFirst({ where: { id: idOf(req), isDeleted: false }, include: serviceInclude }); if (!data) throw new AppError(404, 'Service not found'); ok(res, 'Service retrieved successfully', data); } catch (error) { next(error); } });
services.post('/', auth, requireRole('PROVIDER', 'ADMIN'), async (req, res, next) => { try { const { providerId, ...input } = req.body; ok(res, 'Service created successfully', await prisma.service.create({ data: { ...input, price: Number(input.price), duration: Number(input.duration), providerId: req.user!.role === 'ADMIN' && providerId ? providerId : req.user!.id } }), 201); } catch (error) { next(error); } });
services.patch('/:id', auth, requireRole('PROVIDER', 'ADMIN'), async (req, res, next) => { try { const current = await prisma.service.findUnique({ where: { id: idOf(req) } }); if (!current) throw new AppError(404, 'Service not found'); if (req.user!.role === 'PROVIDER' && current.providerId !== req.user!.id) throw new AppError(403, 'You can only update your own services'); const { providerId: _providerId, ...input } = req.body; ok(res, 'Service updated successfully', await prisma.service.update({ where: { id: current.id }, data: { ...input, ...(input.price !== undefined ? { price: Number(input.price) } : {}), ...(input.duration !== undefined ? { duration: Number(input.duration) } : {}) } })); } catch (error) { next(error); } });
services.delete('/:id', auth, requireRole('PROVIDER', 'ADMIN'), async (req, res, next) => { try { const current = await prisma.service.findUnique({ where: { id: idOf(req) } }); if (!current) throw new AppError(404, 'Service not found'); if (req.user!.role === 'PROVIDER' && current.providerId !== req.user!.id) throw new AppError(403, 'You can only delete your own services'); ok(res, 'Service deleted successfully', await prisma.service.update({ where: { id: current.id }, data: { isDeleted: true } })); } catch (error) { next(error); } });

export const users = Router();
users.use(auth);
users.get('/me', async (req, res, next) => { try { ok(res, 'Profile retrieved successfully', await prisma.user.findUnique({ where: { id: req.user!.id }, omit: { password: true } })); } catch (error) { next(error); } });
users.get('/', requireRole('ADMIN'), async (_req, res, next) => { try { ok(res, 'Users retrieved successfully', await prisma.user.findMany({ where: { isDeleted: false }, omit: { password: true }, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
users.get('/:id', async (req, res, next) => { try { if (req.user!.id !== idOf(req) && req.user!.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); const data = await prisma.user.findFirst({ where: { id: idOf(req), isDeleted: false }, omit: { password: true } }); if (!data) throw new AppError(404, 'User not found'); ok(res, 'User retrieved successfully', data); } catch (error) { next(error); } });
users.patch('/:id', async (req, res, next) => { try { if (req.user!.id !== idOf(req) && req.user!.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); const { password: _password, ...input } = req.body; ok(res, 'User updated successfully', await prisma.user.update({ where: { id: idOf(req) }, data: input, omit: { password: true } })); } catch (error) { next(error); } });
users.delete('/:id', async (req, res, next) => { try { if (req.user!.id !== idOf(req) && req.user!.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); ok(res, 'User deleted successfully', await prisma.user.update({ where: { id: idOf(req) }, data: { isDeleted: true }, omit: { password: true } })); } catch (error) { next(error); } });

export const reviews = Router();
reviews.get('/', async (req, res, next) => { try { ok(res, 'Reviews retrieved successfully', await prisma.review.findMany({ where: { isDeleted: false, ...(req.query.serviceId ? { serviceId: String(req.query.serviceId) } : {}) }, include: { user: { select: { id: true, name: true, avatar: true } }, service: { select: { id: true, title: true } } }, orderBy: { createdAt: 'desc' } })); } catch (error) { next(error); } });
reviews.get('/:id', async (req, res, next) => { try { const data = await prisma.review.findFirst({ where: { id: idOf(req), isDeleted: false } }); if (!data) throw new AppError(404, 'Review not found'); ok(res, 'Review retrieved successfully', data); } catch (error) { next(error); } });
reviews.post('/', auth, async (req, res, next) => { try { const rating = Number(req.body.rating); if (rating < 1 || rating > 5) throw new AppError(400, 'Rating must be between 1 and 5'); ok(res, 'Review saved successfully', await prisma.review.upsert({ where: { userId_serviceId: { userId: req.user!.id, serviceId: req.body.serviceId } }, update: { rating, comment: req.body.comment, isDeleted: false }, create: { serviceId: req.body.serviceId, comment: req.body.comment, rating, userId: req.user!.id } }), 201); } catch (error) { next(error); } });
reviews.patch('/:id', auth, async (req, res, next) => { try { ok(res, 'Review updated successfully', await prisma.review.update({ where: { id: idOf(req), userId: req.user!.id }, data: { ...req.body, ...(req.body.rating !== undefined ? { rating: Number(req.body.rating) } : {}) } })); } catch (error) { next(error); } });
reviews.delete('/:id', auth, async (req, res, next) => { try { ok(res, 'Review deleted successfully', await prisma.review.update({ where: { id: idOf(req), userId: req.user!.id }, data: { isDeleted: true } })); } catch (error) { next(error); } });

const bookingInclude = { customer: { select: { id: true, name: true, email: true } }, service: { include: { category: true, provider: { select: { id: true, name: true } } } } } as const;
export const bookings = Router();
bookings.use(auth);
bookings.get('/provider', requireRole('PROVIDER', 'ADMIN'), async (req, res, next) => { try { ok(res, 'Incoming bookings retrieved successfully', await prisma.booking.findMany({ where: { isDeleted: false, ...(req.user!.role === 'PROVIDER' ? { service: { providerId: req.user!.id } } : {}) }, include: bookingInclude, orderBy: { scheduledAt: 'desc' } })); } catch (error) { next(error); } });
bookings.get('/', async (req, res, next) => { try { ok(res, 'Bookings retrieved successfully', await prisma.booking.findMany({ where: { customerId: req.user!.id, isDeleted: false }, include: bookingInclude, orderBy: { scheduledAt: 'desc' } })); } catch (error) { next(error); } });
bookings.get('/:id', async (req, res, next) => { try { const data = await prisma.booking.findFirst({ where: { id: idOf(req), isDeleted: false, ...(req.user!.role === 'CUSTOMER' ? { customerId: req.user!.id } : {}) }, include: bookingInclude }); if (!data) throw new AppError(404, 'Booking not found'); ok(res, 'Booking retrieved successfully', data); } catch (error) { next(error); } });
bookings.post('/', async (req, res, next) => { try { const service = await prisma.service.findFirst({ where: { id: req.body.serviceId, isDeleted: false, status: 'ACTIVE' } }); if (!service) throw new AppError(404, 'Service not found'); ok(res, 'Booking created successfully', await prisma.booking.create({ data: { serviceId: service.id, scheduledAt: new Date(req.body.scheduledAt), address: req.body.address, note: req.body.note, total: service.price, customerId: req.user!.id } }), 201); } catch (error) { next(error); } });
bookings.patch('/:id', async (req, res, next) => { try { const current = await prisma.booking.findUnique({ where: { id: idOf(req) }, include: { service: true } }); if (!current) throw new AppError(404, 'Booking not found'); const isCustomer = current.customerId === req.user!.id; const isProvider = current.service.providerId === req.user!.id; if (!isCustomer && !isProvider && req.user!.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); const data = req.user!.role === 'CUSTOMER' ? { ...(req.body.status === 'CANCELLED' ? { status: 'CANCELLED' as const } : {}), ...(req.body.address ? { address: req.body.address } : {}), ...(req.body.note !== undefined ? { note: req.body.note } : {}) } : { ...(req.body.status ? { status: req.body.status } : {}), ...(req.body.scheduledAt ? { scheduledAt: new Date(req.body.scheduledAt) } : {}) }; ok(res, 'Booking updated successfully', await prisma.booking.update({ where: { id: current.id }, data })); } catch (error) { next(error); } });
bookings.delete('/:id', async (req, res, next) => { try { const current = await prisma.booking.findUnique({ where: { id: idOf(req) } }); if (!current) throw new AppError(404, 'Booking not found'); if (current.customerId !== req.user!.id && req.user!.role !== 'ADMIN') throw new AppError(403, 'Forbidden'); ok(res, 'Booking deleted successfully', await prisma.booking.update({ where: { id: current.id }, data: { isDeleted: true } })); } catch (error) { next(error); } });
