import express from 'express'; import cors from 'cors'; import helmet from 'helmet';
import authRoutes from './routes/auth.routes.js';
import { bookings } from './routes/booking.routes.js';
import { categories } from './routes/category.routes.js';
import { reviews } from './routes/review.routes.js';
import { services } from './routes/service.routes.js';
import { users } from './routes/user.routes.js';
import { errorHandler } from './middleware/error.js';
import { prisma } from './lib/prisma.js';
import { apiLimiter, authLimiter, requestLogger } from './middleware/production.js';
export const app=express();
app.set('trust proxy', 1); app.disable('x-powered-by');
app.use(requestLogger); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_URL?.split(',')||true,credentials:true})); app.use(express.json({limit:'1mb'})); app.use('/api',apiLimiter);
app.get('/api/health',(_q,r)=>r.json({success:true,message:'Servora API is healthy',data:{timestamp:new Date(),databaseConfigured:Boolean(process.env.DATABASE_URL),jwtConfigured:Boolean(process.env.JWT_SECRET)}}));
app.get('/api/health/database',async(_q,r)=>{try{await prisma.$queryRaw`SELECT 1`;r.json({success:true,message:'Database connection is healthy',data:{connected:true}})}catch(error){const details=error as {name?:string;code?:string;cause?:{code?:string};message?:string};const message=details.message||'';const category=message.includes('does not exist')?'SCHEMA_MISSING':message.toLowerCase().includes('password authentication')?'AUTHENTICATION_FAILED':message.includes('ENOTFOUND')||message.includes('getaddrinfo')?'HOST_UNREACHABLE':message.toLowerCase().includes('ssl')?'SSL_ERROR':message.toLowerCase().includes('timeout')?'CONNECTION_TIMEOUT':'QUERY_FAILED';console.error('Database health check failed',error);r.status(503).json({success:false,message:'Database connection failed',data:{connected:false,category,code:details.code||details.cause?.code||null,name:details.name||'Error'}})}});
app.use('/api/auth',authLimiter,authRoutes); app.use('/api/users',users); app.use('/api/categories',categories); app.use('/api/services',services); app.use('/api/reviews',reviews); app.use('/api/bookings',bookings);
app.use((_q,r)=>r.status(404).json({success:false,message:'Route not found',data:null})); app.use(errorHandler);
